/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_boundary_line = 1,
  sym_final_boundary = 2,
  sym__eol = 3,
  sym_header_name = 4,
  sym_header_value = 5,
  anon_sym_COLON = 6,
  sym_body_line = 7,
  sym_document = 8,
  sym_part = 9,
  sym_header = 10,
  sym_headers = 11,
  sym_body = 12,
  aux_sym_document_repeat1 = 13,
  aux_sym_headers_repeat1 = 14,
  aux_sym_body_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_boundary_line] = "boundary_line",
  [sym_final_boundary] = "final_boundary",
  [sym__eol] = "_eol",
  [sym_header_name] = "header_name",
  [sym_header_value] = "header_value",
  [anon_sym_COLON] = ":",
  [sym_body_line] = "body_line",
  [sym_document] = "document",
  [sym_part] = "part",
  [sym_header] = "header",
  [sym_headers] = "headers",
  [sym_body] = "body",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_headers_repeat1] = "headers_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_boundary_line] = sym_boundary_line,
  [sym_final_boundary] = sym_final_boundary,
  [sym__eol] = sym__eol,
  [sym_header_name] = sym_header_name,
  [sym_header_value] = sym_header_value,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_body_line] = sym_body_line,
  [sym_document] = sym_document,
  [sym_part] = sym_part,
  [sym_header] = sym_header,
  [sym_headers] = sym_headers,
  [sym_body] = sym_body,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_headers_repeat1] = aux_sym_headers_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_boundary_line] = {
    .visible = true,
    .named = true,
  },
  [sym_final_boundary] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_body_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_part] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_headers] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_headers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(sym_body_line);
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == ':') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ':') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_boundary_line);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_final_boundary);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_final_boundary);
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_final_boundary);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_final_boundary);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'B') ADVANCE(19);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'D') ADVANCE(20);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(17);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'O') ADVANCE(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'R') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'U') ADVANCE(18);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'Y') ADVANCE(13);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_header_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_body_line);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'B') ADVANCE(33);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'D') ADVANCE(34);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'N') ADVANCE(31);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'O') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'R') ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'U') ADVANCE(32);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'Y') ADVANCE(38);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_body_line);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 29},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 29},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_boundary_line] = ACTIONS(1),
    [sym_final_boundary] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_body_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(14),
    [sym_part] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [sym_boundary_line] = ACTIONS(3),
    [sym_final_boundary] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(9), 1,
      sym_body_line,
    STATE(7), 1,
      aux_sym_body_repeat1,
    STATE(11), 1,
      sym_body,
    ACTIONS(7), 2,
      sym_boundary_line,
      sym_final_boundary,
  [14] = 3,
    ACTIONS(11), 1,
      sym_header_name,
    STATE(2), 1,
      sym_headers,
    STATE(5), 2,
      sym_header,
      aux_sym_headers_repeat1,
  [25] = 3,
    ACTIONS(3), 1,
      sym_boundary_line,
    ACTIONS(13), 1,
      sym_final_boundary,
    STATE(6), 2,
      sym_part,
      aux_sym_document_repeat1,
  [36] = 3,
    ACTIONS(11), 1,
      sym_header_name,
    ACTIONS(15), 1,
      sym__eol,
    STATE(8), 2,
      sym_header,
      aux_sym_headers_repeat1,
  [47] = 3,
    ACTIONS(17), 1,
      sym_boundary_line,
    ACTIONS(20), 1,
      sym_final_boundary,
    STATE(6), 2,
      sym_part,
      aux_sym_document_repeat1,
  [58] = 3,
    ACTIONS(24), 1,
      sym_body_line,
    STATE(9), 1,
      aux_sym_body_repeat1,
    ACTIONS(22), 2,
      sym_boundary_line,
      sym_final_boundary,
  [69] = 3,
    ACTIONS(26), 1,
      sym__eol,
    ACTIONS(28), 1,
      sym_header_name,
    STATE(8), 2,
      sym_header,
      aux_sym_headers_repeat1,
  [80] = 3,
    ACTIONS(33), 1,
      sym_body_line,
    STATE(9), 1,
      aux_sym_body_repeat1,
    ACTIONS(31), 2,
      sym_boundary_line,
      sym_final_boundary,
  [91] = 2,
    ACTIONS(38), 1,
      sym_body_line,
    ACTIONS(36), 2,
      sym_boundary_line,
      sym_final_boundary,
  [99] = 1,
    ACTIONS(40), 2,
      sym_boundary_line,
      sym_final_boundary,
  [104] = 1,
    ACTIONS(42), 2,
      sym__eol,
      sym_header_name,
  [109] = 1,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
  [113] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
  [117] = 1,
    ACTIONS(48), 1,
      anon_sym_COLON,
  [121] = 1,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
  [125] = 1,
    ACTIONS(52), 1,
      sym_header_value,
  [129] = 1,
    ACTIONS(54), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 25,
  [SMALL_STATE(5)] = 36,
  [SMALL_STATE(6)] = 47,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 69,
  [SMALL_STATE(9)] = 80,
  [SMALL_STATE(10)] = 91,
  [SMALL_STATE(11)] = 99,
  [SMALL_STATE(12)] = 104,
  [SMALL_STATE(13)] = 109,
  [SMALL_STATE(14)] = 113,
  [SMALL_STATE(15)] = 117,
  [SMALL_STATE(16)] = 121,
  [SMALL_STATE(17)] = 125,
  [SMALL_STATE(18)] = 129,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_part, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headers, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headers, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_part, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 1),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_multipart(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "multipart",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
